crawl:
  num_attempts: 1
  dataset:
    uci:
      num_datasets_per_query: 20
    kaggle:
      num_datasets_per_query: 20
key:
  local:
    string: "mongodb://localhost:27017"
    db_name: "coldata"
  remote:
    string: "mongodb+srv://diaoenmao:ColAI2023@crawl-data.5blrkb2.mongodb.net/?retryWrites=true&w=majority&appName=Crawl-Data"
    db_name: "Crawl-Data"
