crawl:
  num_attempts: 1
  dataset:
    uci:
      num_datasets_per_query: 1000
    kaggle:
      init_page: 1
search:
  query: 'A useful dataset'
  topk: 10
mongodb:
  local:
    string: mongodb://localhost:27017
    db_name: coldata
  remote:
    string: mongodb+srv://diaoenmao:ColAI2023@crawl-data.5blrkb2.mongodb.net/?retryWrites=true&w=majority&appName=Crawl-Data
    db_name: Crawl-Data
vdb:
  milvus:
    collection_name: 'dataset'
    alias: default
    host: localhost
    port: '19530'
    index_type: IVF_FLAT
    metric_type: IP
    nlist: 128
    nprobe: 128
    limit: 4
  text:
    chunk_size: 1024
    chunk_overlap: 256
    add_start_index: true
  model:
    model_name: all-mpnet-base-v2
    cache_folder: output/model
    multi_process: False
    show_progress: True
    device: cpu
    normalize_embeddings: False
