crawler:
  website:
    UCI:
      num_attempts: 0
      use_cache: True
      num_datasets_per_query: 1000
    Kaggle:
      num_attempts: 0
      use_cache: True
      init_page: 1
mongodb:
  key:
    local:
      string: mongodb://localhost:27017
      db_name: coldata
    remote:
      string: mongodb+srv://diaoenmao:ColAI2023@crawl-data.5blrkb2.mongodb.net/?retryWrites=true&w=majority&appName=Crawl-Data
      db_name: Crawl-Data
  collection_name: dataset
  index_field: index
vdb:
  milvus:
    collection_name: 'dataset'
    alias: default
    host: localhost
    port: '19530'
    index_type: IVF_FLAT
    metric_type: COSINE
    nlist: 128
    nprobe: 128
    limit: 4
    renew: False
    page_limit: 100
  text:
    chunk_size: 128
    chunk_overlap: 64
    add_start_index: true
  model:
    model_name: all-mpnet-base-v2
    cache_folder: output/model
    multi_process: False
    show_progress: True
    device: cpu
    normalize_embeddings: False
